In [70]:
import numpy as np

#6
#Create a null vector of size 10 but the fifth value which is 1

a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [71]:
#7
#Create a vector with values ranging from 10 to 49

a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [72]:
#8
#Reverse a vector (first element becomes last)

a = np.arange(50)
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [73]:
#9
#Create a 3x3 matrix with values ranging from 0 to 8

a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [74]:
#10
#Find indices of non-zero elements from [1,2,0,0,4,0]

a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


In [75]:
#11
#Create a 3x3 identity matrix

a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [76]:
#12
#Create a 3x3x3 array with random values

a = np.random.rand(3,3,3)
print(a)

[[[0.15752321 0.72549722 0.694776  ]
  [0.06583162 0.70867243 0.03970923]
  [0.11243803 0.98254674 0.8901999 ]]

 [[0.13324544 0.72054763 0.74698549]
  [0.37846815 0.08475403 0.82376785]
  [0.54021355 0.47675143 0.33059836]]

 [[0.41080642 0.98692625 0.29563793]
  [0.71885078 0.00774528 0.44850451]
  [0.95989034 0.28884911 0.64516685]]]


In [77]:
#13
#Create a 10x10 array with random values and find the minimum and maximum values

A = np.random.random((10,10))
Amin, Amax = A.min(), A.max()
print(Amin, Amax)

0.00037104409123989157 0.9994232726898732


In [78]:
#14
#Create a random vector of size 30 and find the mean value

a = np.random.random(30)
b = a.mean()
print(b)

0.4688898674537317


In [79]:
#15
#Create a 2d array with 1 on the border and 0 inside

a = np.ones((15,15))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
