In [52]:
import numpy as np

#6
#Create a null vector of size 10 but the fifth value which is 1

a = np.zeros(10)
a[4] = 1
print(a)
print("\n")


#7
#Create a vector with values ranging from 10 to 49
print("#7")
a = np.arange(10,50)
print(a)
print("\n")


#8
#Reverse a vector (first element becomes last)
print("#8")
a = np.arange(50)
a = a[::-1]
print(a)
print("\n")


#9
#Create a 3x3 matrix with values ranging from 0 to 8
print("#9")
a = np.arange(9).reshape(3,3)
print(a)
print("\n")


#10
#Find indices of non-zero elements from [1,2,0,0,4,0]
print("#10")
a = np.nonzero([1,2,0,0,4,0])
print(a)
print("\n")


#11
#Create a 3x3 identity matrix
print("#11")
a = np.eye(3)
print(a)
print("\n")


#12
#Create a 3x3x3 array with random values
print("#12")
a = np.random.rand(3,3,3)
print(a)
print("\n")


#13
#Create a 10x10 array with random values and find the minimum and maximum values
print("#13")
A = np.random.random((10,10))
Amin, Amax = A.min(), A.max()
print(Amin, Amax)
print("\n")


#14
#Create a random vector of size 30 and find the mean value
print("#14")
a = np.random.random(30)
b = a.mean()
print(b)
print("\n")


#15
#Create a 2d array with 1 on the border and 0 inside
print("#15")
a = np.ones((15,15))
a[1:-1,1:-1] = 0
print(a)
print("\n")


#16
#

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#7
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#8
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#9
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#10
(array([0, 1, 4], dtype=int64),)


#11
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#12
[[[0.91829585 0.82937449 0.56986679]
  [0.353205   0.19560781 0.53180343]
  [0.8612063  0.59072887 0.79427835]]

 [[0.60023726 0.38667144 0.36745885]
  [0.5438884  0.94361952 0.69801009]
  [0.30742832 0.86328264 0.7573386 ]]

 [[0.22306532 0.24856153 0.07215306]
  [0.32699057 0.02969711 0.4764857 ]
  [0.43305691 0.99597605 0.74301107]]]


#13
0.023601993473155836 0.9464480885504198


#14
0.502719883644627


#15
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 