In [66]:
import numpy as np

#16
#How to add a border (filled with 0's) around an existing array?
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)
print("\n")

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]




In [67]:
#17
#What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [68]:
#18
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [69]:
#19
#Create a 8x8 matrix and fill it with a checkerboard pattern

a = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [70]:
#20
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [71]:
#21
#Create a checkerboard 8x8 matrix using the tile function

a = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [72]:
#22
#Normalize a 5x5 random matrix

a = np.random.random((5,5))
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print(a)

[[0.79187405 0.48539833 0.42782056 0.52669434 0.42030184]
 [0.69565554 1.         0.3744802  0.63063594 0.18598973]
 [0.08129131 0.51474101 0.95479328 0.10704239 0.73079278]
 [0.         0.11303924 0.05333614 0.51352566 0.47985804]
 [0.57421039 0.04607918 0.88715068 0.72840933 0.1404833 ]]


In [73]:
#23
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [74]:
#24
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [75]:
#25
#Given a 1D array, negate all elements which are between 3 and 8, in place.

a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [76]:
#26
#What is the output of the following script?
# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))


print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [77]:
#27
#Consider an integer vector Z, which of these expressions are legal?
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z



In [78]:
#28
#What are the result of the following expressions?
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)



In [79]:
#29
#How to round away from zero a float array ?

a = np.random.uniform(-10,+10,10)
print (np.trunc(a + np.copysign(0.5, a)))

[ 4.  5. -7.  7. -1.  8.  9. -3. -5. -6.]


In [80]:
#30
#How to find common values between two arrays?

array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]
