In [18]:
import numpy as np

#31
#How to ignore all numpy warnings (not recommended)?

np.warnings.filterwarnings('ignore')

In [19]:
#32
#Is the following expressions true?
#np.sqrt(-1) == np.emath.sqrt(-1)

import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [20]:
# 33
# How to get the dates of yesterday, today and tomorrow?

import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2018-12-19
Today:  2018-12-20
Tomorrow:  2018-12-21


In [21]:
# 34
# How to get all the dates corresponding to the month of July 2016?

import numpy as np
print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


In [22]:
# 35
# How to compute ((A+B)*(-A/2)) in place (without copy)?



In [23]:
# 36
# Extract the integer part of a random array using 5 different methods

import numpy as np
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[3. 4. 8. 2. 2. 2. 0. 4. 2. 0.]
[3. 4. 8. 2. 2. 2. 0. 4. 2. 0.]
[3. 4. 8. 2. 2. 2. 0. 4. 2. 0.]
[3 4 8 2 2 2 0 4 2 0]
[3. 4. 8. 2. 2. 2. 0. 4. 2. 0.]


In [24]:
# 37
# Create a 5x5 matrix with row values ranging from 0 to 4

import numpy as np
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [26]:
# 38
# Consider a generator function that generates 10 integers and use it to build an array 

import numpy as np
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [27]:
# 39
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [29]:
# 40
# Create a random vector of size 10 and sort it

Z = np.random.random(10)
Z.sort()
print(Z)

[0.12908716 0.17670654 0.272167   0.35477066 0.38957399 0.55104112
 0.68691552 0.69758432 0.77250535 0.86726812]
