In [15]:
import numpy as np 
a = np.linspace(10,20, 3) 
print(a)
print("\n")

a = np.linspace(10, 20, 5) 
print(a)
print("\n")

a = np.linspace(10,20, 5, endpoint = False) #doesn't displays the last value
print(a)
print("\n")

a = np.linspace(10,20, 5, retstep=True) #displays the spacing between the consecutive numbers
print(a)
print("\n")

[10. 15. 20.]


[10.  12.5 15.  17.5 20. ]


[10. 12. 14. 16. 18.]


(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)


