In [3]:
import numpy as np

zeros = np.zeros(5)
print(zeros)

ones = np.ones(5)
print(ones)

two_d = np.zeros((3,5))
print(two_d)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
